### ISSUE TITLE
opencv-python>=4.1.2

### ISSUE THREAD

**Issue by 1311523821** [lmomoy/LF-YOLO#1]
hello，When I was running your code, there was a problem with the version of OpenCV。My opencv   is 4.5.2, but He reminded me opencv-python>=4.1.2

requirements: opencv-python>=4.1.2 not found and is required by YOLOv3, attempting auto-update...
ERROR: Invalid requirement: "'opencv-python"
Traceback (most recent call last):
  File "d:\Studies\bhdx\CODE\LF-YOLO-master\utils\general.py", line 110, in check_requirements
    pkg.require(r)
  File "D:\Studies\Anaconda3\envs\pytorch\lib\site-packages\pkg_resources\__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\Studies\Anaconda3\envs\pytorch\lib\site-packages\pkg_resources\__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'opencv-python>=4.1.2' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/Studies/bhdx/CODE/LF-YOLO-master/train.py", line 511, in <module>
    check_requirements()
  File "d:\Studies\bhdx\CODE\LF-YOLO-master\utils\general.py", line 114, in check_requirements
    print(subprocess.check_output(f"pip install '{e.req}'", shell=True).decode())
  File "D:\Studies\Anaconda3\envs\pytorch\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Studies\Anaconda3\envs\pytorch\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install 'opencv-python>=4.1.2'' returned non-zero exit status 1.

Do you have this problem？

**Comment by lmomoy** [comment]
I have not met your problem, and my opencv-python version is 4.5.1.48.
